# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      taskId:
        required: true
        type: string
      environment:
        required: true
        type: string
      unique_identifier: 
        required: true
        type: string
      client_ids:
        required: true
        type: string
      konduto_private_key: 
        required: true
        type: string
      paypal:
        required: true
        type: string
      mercadopago:
        required: true
        type: string
      mundipagg:
        required: true
        type: string
      payzen:
        required: true
        type: string
      paymee:
        required: true
        type: string
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hello world
        run: |
          echo Logs!
          echo taskId: ${{ inputs.taskId }}
          echo environment: ${{ inputs.environment }}
          echo unique_identifier: ${{ inputs.unique_identifier }}
          echo client_ids: ${{ inputs.client_ids }}
          echo konduto_private_key: ${{ inputs.konduto_private_key }}
          echo paypal: ${{ inputs.paypal }}
          echo mercadopago: ${{ inputs.mercadopago }}
          echo mundipagg: ${{ inputs.mundipagg }}
          echo payzen: ${{ inputs.payzen }}
          echo paymee: ${{ inputs.paymee }}
