# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      taskId:
        required: true
        type: string
      unique_identifier:
        required: true
        type: string
      client_ids:
        required: true
        type: string
      environment:
        required: true
        type: string
      ## Anti-fraud
      konduto_private_key:
        required: true
        type: string
      ## Means of payment
      paypal:
        required: true
        type: string
      mercadopago:
        required: true
        type: string
      mundipagg:
        required: true
        type: string
      payzen:
        required: true
        type: string
      paymee:
        required: true
        type: string
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hello world
        run: |
          echo Hello, world!
          echo Card Name: ${{ github.event.inputs.taskId }}
          echo Card Name: ${{ github.event.inputs.unique_identifier }}
          echo Card Name: ${{ github.event.inputs.client_ids }}
          echo Card Name: ${{ github.event.inputs.konduto_private_key }}
          echo Card Name: ${{ github.event.inputs.paypal }}
          echo Card Name: ${{ github.event.inputs.mercadopago }}
          echo Card Name: ${{ github.event.inputs.mundipagg }}
          echo Card Name: ${{ github.event.inputs.payzen }}
          echo Card Name: ${{ github.event.inputs.paymee }}
