# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      cardName:
        required: true
        type: string
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hello world
        run: |
          echo Hello, world!
          echo Card Name: ${{ github.event.inputs.cardName }}.
