# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      taskId:
        description: 'Task ID'
        required: true
      unique_identifier:
        description: 'Domain Unique Identifier'
        required: true
      client_ids:
        description: 'Whitelabel client id. Ex.: 10940,10941,10942'
        required: true
      environment:
        type: choice
        required: true
        description: 'Whitelabel development use cabal'
        default: 'cabal'
        options: 
        - cabal
        - live
        - staging
      ## Anti-fraud
      konduto_private_key:
        description: 'Konduto private key'
        required: true
      ## Means of payment
      paypal:
        description: 'PayPal Private Key Identifier'
        default: 'whitelabel'
        required: true
      mercadopago:
        description: 'MercadoPago Private Key Identifier'
        default: 'nofluxo'
        required: true
      mundipagg:
        description: 'MundiPagg Private Key Identifier'
        default: 'whitelabel'
        required: true
      payzen:
        description: 'Payzen Private Key Identifier'
        default: 'whitelabel'
        required: true
      paymee:
        description: 'Paymee Private Key Identifier'
        default: 'wl_pix'
        required: true
  workflow_call:
    inputs:
      taskId:
        required: true
        type: string
      environment:
        required: true
        type: string
      unique_identifier: 
        required: true
        type: string
      client_ids:
        required: true
        type: string
      konduto_private_key: 
        required: true
        type: string
      paypal:
        required: true
        type: string
      mercadopago:
        required: true
        type: string
      mundipagg:
        required: true
        type: string
      payzen:
        required: true
        type: string
      paymee:
        required: true
        type: string
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hello world
        run: |
          echo Logs!
          echo taskId: ${{ inputs.taskId }}
          echo environment: ${{ inputs.environment }}
          echo unique_identifier: ${{ inputs.unique_identifier }}
          echo client_ids: ${{ inputs.client_ids }}
          echo konduto_private_key: ${{ inputs.konduto_private_key }}
          echo paypal: ${{ inputs.paypal }}
          echo mercadopago: ${{ inputs.mercadopago }}
          echo mundipagg: ${{ inputs.mundipagg }}
          echo payzen: ${{ inputs.payzen }}
          echo paymee: ${{ inputs.paymee }}
